namespace SrtGuid.Core
{
    /// <summary>The version of the underlying Guid, used to create the ShortGuid.</summary>
    public enum ShortGuidVersion
    {
        /// <summary>Randomly generated bytes (besides the version, and variant sections).</summary>
        Version4,

        /// <summary>Time-ordered, then filled out with random bytes for the remaining bits (besides the version, and variant sections).</summary>
        Version7
    }
}
